export const ALL_DISEASES_REQUEST = "ALL_DISEASES_REQUEST";
export const ALL_DISEASES_SUCCESS = "ALL_DISEASES_SUCCESS";
export const ALL_DISEASES_FAIL = "ALL_DISEASES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const DISEASE_DETAILS_REQUEST = "DISEASE_DETAILS_REQUEST";
export const DISEASE_DETAILS_SUCCESS = "DISEASE_DETAILS_SUCCESS";
export const DISEASE_DETAILS_FAIL = "DISEASE_DETAILS_FAIL";

export const ADMIN_DISEASES_REQUEST = "ADMIN_DISEASES_REQUEST";
export const ADMIN_DISEASES_SUCCESS = "ADMIN_DISEASES_SUCCESS";
export const ADMIN_DISEASES_FAIL = "ADMIN_DISEASES_FAIL";

export const NEW_DISEASE_REQUEST = "NEW_DISEASE_REQUEST";
export const NEW_DISEASE_SUCCESS = "NEW_DISEASE_SUCCESS";
export const NEW_DISEASE_RESET = "NEW_DISEASE_RESET";
export const NEW_DISEASE_FAIL = "NEW_DISEASE_FAIL";

export const DELETE_DISEASE_REQUEST = "DELETE_DISEASE_REQUEST";
export const DELETE_DISEASE_SUCCESS = "DELETE_DISEASE_SUCCESS";
export const DELETE_DISEASE_RESET = "DELETE_DISEASE_RESET";
export const DELETE_DISEASE_FAIL = "DELETE_DISEASE_FAIL";

export const UPDATE_DISEASE_REQUEST = "UPDATE_DISEASE_REQUEST";
export const UPDATE_DISEASE_SUCCESS = "UPDATE_DISEASE_SUCCESS";
export const UPDATE_DISEASE_RESET = "UPDATE_DISEASE_RESET";
export const UPDATE_DISEASE_FAIL = "UPDATE_DISEASE_FAIL";